// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {payload} from '../models';
import {model} from '../models';

export function CreateCategory(arg1:payload.CreateCategory):Promise<model.Category>;

export function GetCategories():Promise<Array<model.Category>>;
