// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCategory(arg1) {
  return window['go']['category']['CategoryService']['CreateCategory'](arg1);
}

export function GetCategories() {
  return window['go']['category']['CategoryService']['GetCategories']();
}
