// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateResource(arg1) {
  return window['go']['resource']['Service']['CreateResource'](arg1);
}

export function GetResources() {
  return window['go']['resource']['Service']['GetResources']();
}

export function LoadResourceData(arg1) {
  return window['go']['resource']['Service']['LoadResourceData'](arg1);
}
