// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {payload} from '../models';
import {model} from '../models';
import {dto} from '../models';

export function CreateResource(arg1:payload.CreateResource):Promise<model.Resource>;

export function GetResources():Promise<Array<model.Resource>>;

export function LoadResourceData(arg1:payload.LoadResourceData):Promise<dto.ResourceData>;
